valid=find(arrayfun(@(x)(~isnan(x.MeanPosFwd)),Megadatabase));
Megavalid=Megadatabase(valid);

MeanElbowFlex = find(arrayfun(@(x)(strcmp(x.Signal,'ElbowFlex')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDElbowFlex = find(arrayfun(@(x)(strcmp(x.Signal,'ElbowFlex')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

MeanShoulderPlane = find(arrayfun(@(x)(strcmp(x.Signal,'Shoulderplane')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDShoulderPlane = find(arrayfun(@(x)(strcmp(x.Signal,'Shoulderplane')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

MeanShoulderEle = find(arrayfun(@(x)(strcmp(x.Signal,'ShoulderElev')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDShoulderEle = find(arrayfun(@(x)(strcmp(x.Signal,'ShoulderElev')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

MeanTrunkRx = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRx')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDTrunkRx = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRx')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

MeanTrunkRy = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRy')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDTrunkRy = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRy')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

MeanTrunkRz = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRz')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'Mean')),Megavalid));
SDTrunkRz = find(arrayfun(@(x)(strcmp(x.Signal,'TrunkRz')),Megavalid) & ...
    arrayfun(@(x)(strcmp(x.Stat,'SD')),Megavalid));

%% Database with all computed variables 
DataBaseRPT.AllX = [Megavalid(MeanElbowFlex).MeanPosFwd;Megavalid(MeanElbowFlex).ROMFwd; ...
    Megavalid(SDElbowFlex).MeanPosFwd;Megavalid(SDElbowFlex).ROMFwd; ...
    Megavalid(MeanShoulderPlane).MeanPosFwd;Megavalid(MeanShoulderPlane).ROMFwd; ...
    Megavalid(SDShoulderPlane).MeanPosFwd;Megavalid(SDShoulderPlane).ROMFwd; ...
    Megavalid(MeanShoulderEle).MeanPosFwd;Megavalid(MeanShoulderEle).ROMFwd; ...
    Megavalid(SDShoulderEle).MeanPosFwd;Megavalid(SDShoulderEle).ROMFwd; ...
    Megavalid(MeanTrunkRx).MeanPosFwd;Megavalid(MeanTrunkRx).ROMFwd; ...
    Megavalid(SDTrunkRx).MeanPosFwd;Megavalid(SDTrunkRx).ROMFwd; ...
    Megavalid(MeanTrunkRy).MeanPosFwd;Megavalid(MeanTrunkRy).ROMFwd; ...
    Megavalid(SDTrunkRy).MeanPosFwd;Megavalid(SDTrunkRy).ROMFwd; ...
    Megavalid(MeanTrunkRz).MeanPosFwd;Megavalid(MeanTrunkRz).ROMFwd; ...
    Megavalid(SDTrunkRz).MeanPosFwd;Megavalid(SDTrunkRz).ROMFwd;];

DataBaseRPT.CAssignAll={'AveElbFlexMean', 'ROMElbFlexMean', ...
    'AveElbFlexSD', 'ROMElbFlexSD', 'AveShPlaneMean', 'ROMShPlaneMean', ...
    'AveShPlaneSD', 'ROMShPlaneSD', 'AveShEleMean', 'ROMShEleMean', ...
    'AveShEleSD', 'ROMShEleSD', 'AveTrXMean', 'ROMTrXMean', 'AveTrXSD', 'ROMTrXSD', ... 
    'AveTrYMean', 'ROMTrYMean', 'AveTrYSD', 'ROMTrYSD', ...
    'AveTrZMean', 'ROMTrZMean', 'AveTrZSD', 'ROMTrZSD'};

%% Database with only the highly responsives variables (SRM > 0.8, Bouffard et al 2018)
DataBaseRPT.BestX = [Megavalid(MeanShoulderEle).MeanPosFwd; ...
    Megavalid(MeanTrunkRx).MeanPosFwd; Megavalid(MeanTrunkRx).ROMFwd; ...
    Megavalid(SDTrunkRx).MeanPosFwd;Megavalid(SDTrunkRx).ROMFwd; ...
    Megavalid(MeanTrunkRy).ROMFwd; ...
    Megavalid(MeanTrunkRz).MeanPosFwd];

DataBaseRPT.CAssignBest={'AveShEleMean', 'AveTrXMean', 'ROMTrXMean', ...
    'AveTrXSD', 'ROMTrXSD','ROMTrYMean', 'AveTrZMean'};

%% Other inputs to the database

DataBaseRPT.Y = arrayfun(@(x)(x.Time),Megavalid(MeanElbowFlex));
DataBaseRPT.Sex = arrayfun(@(x)(x.Sex),Megavalid(MeanElbowFlex));
DataBaseRPT.Endurance = arrayfun(@(x)(x.Endurance),Megavalid(MeanElbowFlex));
DataBaseRPT.Age = arrayfun(@(x)(x.Age),Megavalid(MeanElbowFlex));
DataBaseRPT.Height = arrayfun(@(x)(x.Height),Megavalid(MeanElbowFlex));
DataBaseRPT.Weight = arrayfun(@(x)(x.Weight),Megavalid(MeanElbowFlex));
DataBaseRPT.SubjectKey = arrayfun(@(x)(x.Subject),Megavalid(MeanElbowFlex));
DataBaseRPT.SID = arrayfun(@(x)(x.SubjectID),Megavalid(MeanElbowFlex));
