function [pind,data] = clean_dataRPT(data,signal,name)
% Clean_data allows to select data from the plot and replace it (by NaN, 0 or [])
% Input data should be nframe * observations
%
% Bad data selector is a brush, so you can click and slide over all data
% you want to remove at once. Click on Update to see the data without the
% bad movements. Click on Close once you are happy with the remaining data.
%
% Problems with the method: 
% - The brush is big, so impossible to select trials that are obviously strange, but too close to valid trials.
% - No way to cancel changes

% figure
S.fh = figure('units','normalized',...
    'outerposition',[0.1 0.1 0.8 0.8],...
    'menubar','none',...
    'numbertitle','off',...
    'name',name,...
    'resize','off');
% axes
S.ax = axes('units','normalized',...
    'position',[0.05 0.1 0.8 0.8],...
    'fontsize',8,...
    'nextplot','replacechildren');
S.ax.YLabel.String = signal;
% update button
S.but = uicontrol('style','push',...
    'units','normalized',...
    'position',[0.87 0.5 0.1 0.05],...
    'fontsize',14,...
    'string','update',...
    'Callback',{@but_funct,S});

% close button
S.clo = uicontrol('style','push',...
    'units','normalized',...
    'position',[0.87 0.4 0.1 0.05],...
    'fontsize',14,...
    'string','close', ...
    'Callback',@(h,e)closeFig(h,e,S));

    while ishandle(S.fh)
        uiwait(S.fh);
    end
    function but_funct(varargin)
        plot(data)
		        
        [pind] = selectdata('selectionmode','Brush');
        
        pind = pind(end:-1:1);
                
        data(:,~cellfun('isempty', pind)) = NaN;
    end

    function closeFig(varargin) 
        S = varargin{3};
        delete(S.fh)
    end
end